api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        json:
            mime_types: ['application/json']

        jsonld:
            mime_types: ['application/ld+json']
            
        html:
            mime_types: ['text/html']
    collection:
        # The default order of results.
        order: 'ASC'

        # The name of the query parameter to order results.
        order_parameter_name: 'order'

        pagination:
            # To allow the client to set the number of items per page.
            client_items_per_page: true

            # The default number of items per page.
            items_per_page: 10